#cloud-config

packages:
  - net-tools

runcmd:
  - sudo apt install lsb-release -y
  - curl -fsSL "https://packages.redis.io/gpg" | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
  - sudo apt-get update
  - sudo apt-get install redis -y
  - /etc/redis/redis-init.sh

write_files:
  - content:  |
      {{ redis_init }}
    path: /etc/redis/redis-init.sh
    permissions: '0755'